make video responsive
shiva-infobeans/parakh2 pull request #276
Opened 2016-12-20 13:57 UTC by anand-infobeans

2016-12-20 15:23 UTC, rsonar-infobeans requested changes

2016-12-20 15:23 UTC, rsonar-infobeans commented on css/custom.css
> +>>>>>>> devrc2
There is a conflict code

2016-12-20 15:23 UTC, rsonar-infobeans commented on parakh-new/include/dbmodule.php
> +        $video = '<video class="video" id="parakh_video" controls="" loop="" ><source type="video/ogg" src="Parakh_Teaser.mp4"><source type="video/mp4" src="Parakh_Teaser.mp4"><object  type="applicat
You don't need to call PHP for video URL. you can keep this video URL in javascript variable

2016-12-20 15:23 UTC, rsonar-infobeans commented on js/views/login.html
>         	<img src="images/2016-12-11.gif">
Why this file is named like this?

2016-12-21 04:42 UTC, anand-infobeans commented on js/views/login.html
>         	<img src="images/2016-12-11.gif">
I thought that was login module so I named login.html. 

Where all login related views and event are handled.

2016-12-21 04:43 UTC, anand-infobeans commented on parakh-new/include/dbmodule.php
> +        $video = '<video class="video" id="parakh_video" controls="" loop="" ><source type="video/ogg" src="Parakh_Teaser.mp4"><source type="video/mp4" src="Parakh_Teaser.mp4"><object  type="applicat
I made a var in javascript now but whenever modal will open loader image will not show because it loads video directly

2016-12-21 04:43 UTC, anand-infobeans commented on css/custom.css
> +>>>>>>> devrc2
Conflict code resolved successfully

2016-12-23 14:00 UTC, merged